### ISSUE TITLE
Failed to compile template

### ISSUE THREAD

**Issue by shah-iq** [maizzle/starter-markdown#2]
I followed the exact steps as mentioned in the [article](https://maizzle.com/guides/markdown-emails) on how to create an HTML email newsletter from Markdown files but got an error at the last `npm run build` command when compiling the markdown files. Can you please let me know on how to resolve this?

![image](https://user-images.githubusercontent.com/108127296/222226452-5f0bbd57-7d4e-461d-9fd8-010cc787f994.png)

**Comment by cossssmin** [comment]
Hey, sorry I missed this. Looks like there's an issue with your CSS, maybe there's a typo or something in there. If this is still an issue and you can share a repo that I can look at (can be private too), I'll be happy to help :)

**Comment by shah-iq** [comment]
I resolved this and indeed there was an issue with CSS. Thank you.
